### ISSUE TITLE
Is there any plan to release the pretrained model weights?

### ISSUE THREAD

**Issue by xperzy** [MonashAI/HVT#1]
Is there any plan to release the pretrained model weights?

**Comment by HubHop** [comment]
Hi @xperzy, 

Thanks for your interest! We have just released the pretrained weights for most of the models reported in our paper. Please check out [here](https://github.com/zhuang-group/HVT/releases/tag/v1.0). Unfortunately, we lost the checkpoint for HVT-S-1. For this, we will retrain this model in the next coming days and will release the pretrained weights in the near future.

Best,
Zizheng

**Comment by HubHop** [comment]
Hi @xperzy,

We have uploaded the model weights as well as the log for HVT-S-1. The retrained model achieves 77.99% in Top-1 accuracy on ImageNet, which is almost consistent with the reported result in our paper (78.00%). Please do not hesitate to contact us if you have any further questions.

Cheers,
Zizheng

**Comment by xperzy** [comment]
@HubHop Thanks for the release !
